### ISSUE TITLE
Unifying netCDF/HDF versions across components

### ISSUE THREAD

**Issue by russfiedler** [COSIMA/access-om2#147]
At the moment the various components appear to be built with different netCDF versions by default. There really should be a common version used. This  is important in the light of problems with some of the libraries. See here for issues if we move to PIO for CICE. https://github.com/COSIMA/cice5/issues/34

**Comment by aekiss** [comment]
`libcheck.sh` provides overview of the libraries used

**Comment by russfiedler** [comment]
Yes it provides an overview and it's how I spotted all the different libraries being used. The thing is that, ideally, they should be consistent in the first place.

**Comment by aekiss** [comment]
I agree - it was just a FYI but you already knew...

**Comment by nichannah** [comment]
libcheck.sh now reports netcdf/4.3.2 being used for all submodels.

**Comment by aekiss** [comment]
Hi @nichannah I've encountered something weird - when I compile this latest version with `install.sh`, libcheck.sh gives me the wrong netcdf version
```
      /short/v45/aek156/sources/new/access-om2/src/libaccessom2/build/bin/yatm.exe:
	libnetcdff.so.6 => /apps/netcdf/4.4.1.1/lib/libnetcdff.so.6 (0x00007fe62dbae000)
	libnetcdf.so.11 => /apps/netcdf/4.4.1.1/lib/libnetcdf.so.11 (0x00007fe62a7db000)
```
This seems to be due to `install.sh`: https://github.com/COSIMA/access-om2/blob/21d92b55544c98968dc0ba11caaaf7e7e0f326e4/install.sh#L39
When I recompile with that line removed I get
```
      /short/v45/aek156/sources/new/access-om2/src/libaccessom2/build/bin/yatm.exe:
	libnetcdff.so.6 => not found
	libnetcdf.so.11 => not found
```
so for some reason it's not picking up `module load netcdf/4.3.2` from `build_on_raijin.sh`. 

`install.sh` uses cmake and make - does this even use `build_on_raijin.sh`?

**Comment by aekiss** [comment]
I've set `install.sh` to use `build_on_raijin.sh` in https://github.com/COSIMA/access-om2/commit/488b08419a52fedb54126a30ea0649f54c13a50d
but `build_on_raijin.sh` has an issue: https://github.com/COSIMA/libaccessom2/issues/24

**Comment by nichannah** [comment]
Re our TWG discussion, do we now want to upgrade again to netcdf/4.7.1?

**Comment by nichannah** [comment]
Closing this for now, we can do upgrade as a separate issue.
