### ISSUE TITLE
mppnccombine needs to be compiled for Gadi

### ISSUE THREAD

**Issue by penguian** [COSIMA/access-om2#177]
The executable `mppnccombine` needs to be compiled for Gadi.

Running the `1deg_jar55_ryf` experiment on Gadi results in error messages in postprocessing such as:
```
payu: error: Thread 0 crashed with error code 127.
 Error message:
/g/data/fp0/pcl900/bin/mppnccombine: error while loading shared libraries: libnetcdf.so.7: cannot open shared object file: No such file or directory
```
The executable `mppnccombine` here
```
[pcl900@gadi-login-04 pcl900]$ file /g/data/fp0/pcl900/bin/mppnccombine
/g/data/fp0/pcl900/bin/mppnccombine: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=0a1336e90ca8fd54c9ed820ce85cd35be740dad4, stripped
```
is a copy of `raijin:/short/public/access-om2/bin/mppnccombine`.

I haven't been able to find a build script or installation instructions for `mppnccombine` specific to Raijin, although I have found source code at https://github.com/mom-ocean/MOM5/tree/master/src/postprocessing/mppnccombine

**Comment by aekiss** [comment]
Thanks for catching this Paul. `install.sh` builds mppnccombine. 

Looks like we need to update the netcdf library version in MOM5 [bin/environs.nci](https://github.com/mom-ocean/MOM5/blob/master/bin/environs.nci)

We want to make this uniform across model components, and it looks like 4.7.1 would be a good choice - see https://github.com/COSIMA/access-om2/issues/166

**Comment by russfiedler** [comment]
`mppnccombine.nci` won't get built if there is already a copy of it existing in the directory `access-om2/src/mom/bin/`. It gets copied by `hashexe.sh` to `access-om2/bin/mppnccombine`. You need to remove the existing `mppnccombine.nci` to update the executable.

Note that if you've created a new bin/environs.gadi say (setting --platform gadi in the MOM compilation) for the new machine mppnccombine.nci is hardwired as a name rather than using the $platform variable and won't get updated.

**Comment by aekiss** [comment]
Thanks for pointing that out @russfiedler - I've just amended `install.sh` to force recompilation of `mppnccompile.nci`: https://github.com/COSIMA/access-om2/commit/ee555d32442f633038d1712acb3be82474769d7e
