### ISSUE TITLE
Check that physical constants are consistent across models

### ISSUE THREAD

**Issue by nichannah** [COSIMA/access-om2#22]
We've been tripped up several times by differences in physical constants between MOM and CICE and between the core MOM and ACCESS MOM code. 

We need to implement some tests so that this doesn't happen again. 

In addition it might might be a good idea to set these values in one place only rather than have them defined separately in different submodules.

**Comment by ofa001** [comment]
This was raised a few weeks ago when you closed the heat content budget but have now got a non-closed ice budget issue due to ref-density and heat capacity difference, common heat capacity setting is more easily done, common reference density needs to be upper ocean value to be meaningful for ice and atmosphere models. Other basic physical constants also need to be set identical across all models all models.

**Comment by aekiss** [comment]
I'm working on a namelist comparison tool based on [f90nml](http://f90nml.readthedocs.io/en/latest/) that could be helpful for this. At present it can list the semantic differences between any number of nml files. This would be useful for keeping track of changes across different config/runs. Comparing physical parameters across model components (eg MOM & CICE) is less straightforward - we'd need a table of the differing names used for the same physical parameter in different model components.

**Comment by nichannah** [comment]
Also see https://github.com/OceansAus/access-om2/issues/76

**Comment by nichannah** [comment]
Closing this issue as a duplicate with #76
